require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'
# Add the following line at the top of Podfile.
# Codegen produces files/classes that share names, and it will show the warning.
# deterministic_uuids option surpresses the warning.
install! 'cocoapods', :deterministic_uuids => false

platform :ios, '11.0'

def pods()
  # // Get config
  config = use_native_modules!

  # // Use env variables to turn it on/off.
  fabric_enabled = ENV['USE_FABRIC']
  use_codegen_discovery= ENV['USE_CODEGEN_DISCOVERY']

  # // Enabled codegen discovery. This will run the codegen at preinstall time.
  # // Files are generated at {pod installation root}/build/generated/ios/
  use_react_native!(
    path: config[:reactNativePath],
    fabric_enabled: fabric_enabled,
    hermes_enabled: false,
    app_path: "#{Dir.pwd}/..",
  )

  # use_react_native!(
  #   :path => config[:reactNativePath],
  #   # to enable hermes on iOS, change `false` to `true` and then install pods
  #   :hermes_enabled => false,
  #   :fabric_enabled => fabric_enabled
  # )
end


target 'myTurbo2' do
  pods()
  config = use_native_modules!



  target 'myTurbo2Tests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable the next line.
  use_flipper!()

  post_install do |installer|
    react_native_post_install(installer)
    __apply_Xcode_12_5_M1_post_install_workaround(installer)
  end
end
